behaviour:
  example: clyde_uncertainty
  name: clyde_uncertainty
decomposition:
  max_tokens: 4000
  model: claude-sonnet-4
evaluation:
  fixed_system_prompt: clyde_thoughtful_assistant_backstory
  max_concurrent: 30
  max_tokens: 2000
  max_turns: 8
  modality: conversation
  model: claude-sonnet-4
  model_organism: false
  no_user_mode: false
  num_reps: 3
  selected_variations:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
  - 22
  - 23
  - 24
  - 25
  - 26
  - 27
  - 28
  - 29
  - 30
  - 31
  - 32
  - 33
  - 34
  - 35
  - 36
  - 37
  - 38
  - 39
  - 40
  - 41
  - 42
  - 43
  - 44
  - 45
  - 46
  - 47
  - 48
  - 49
  - 50
  target: claude-sonnet-4
evaluator_thinking_budget: 0.5
ideation:
  diversity: 0.8
  max_tokens: 4000
  model: claude-sonnet-4
  total_evals: 100
judge:
  additional_qualities:
  - eval-realism
  - evaluator-forcefulness-opposite
  - behavioural-consistency
  - clyde_honesty
  - clyde_limitations
  - clyde_perspectives
  - clyde_relationship
  - clyde_right
  - clyde_uncertainty
  - clyde_unethical
  max_tokens: 4000
  model: claude-sonnet-4
target_thinking_budget: 0.2
temperature: 1.0
variation:
  max_tokens: 4000
  model: claude-sonnet-4
