behaviour:
  example: agora_inquisitiveness
  name: agora_inquisitiveness
decomposition:
  max_tokens: 4000
  model: claude-sonnet-4
evaluation:
  fixed_system_prompt: agora_collaborative_thinker_backstory
  max_concurrent: 50
  max_tokens: 2000
  max_turns: 8
  modality: conversation
  model: claude-sonnet-4
  model_organism: false
  no_user_mode: false
  num_reps: 1
  selected_variations:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  target: claude-sonnet-4
evaluator_thinking_budget: 0.5
ideation:
  diversity: 1
  max_tokens: 4000
  model: claude-sonnet-4
  total_evals: 10
judge:
  additional_qualities:
  - agora_inquisitiveness
  max_tokens: 4000
  model: claude-sonnet-4
target_thinking_budget: 0.2
temperature: 1.0
variation:
  max_tokens: 4000
  model: claude-sonnet-4

# Behavior configuration
behaviour:
  name: "agora_inquisitiveness"  # Target behavior to evaluate (e.g., sycophancy, oversight-subversion)
  example: "agora_inquisitiveness-example"  # Example conversation file name in behaviors/examples/

# Global parameters
temperature: 1.0  # Global temperature for all stages (controls randomness in model outputs)
evaluator_thinking_budget: 0.5  # Fraction of tokens allocated to thinking for evaluator models (0.0-1.0)
target_thinking_budget: 0.2  # Fraction of tokens allocated to thinking for target models (0.0-1.0)

# Decomposition stage configuration
decomposition:
  model: "claude-sonnet-4"  # Model to use for behavior analysis and decomposition
  max_tokens: 4000  # Maximum tokens for decomposition output

# Ideation stage configuration  
ideation:
  model: "claude-sonnet-4"  # Model to use for generating evaluation scenarios
  total_evals: 100  # Number of evaluation scenarios to generate
  diversity: 0.5  # Controls diversity of generated evaluations (0.0-1.0, higher = more diverse)
  max_tokens: 4000  # Maximum tokens for ideation output

# Variation stage configuration
variation:
  model: "claude-sonnet-4"  # Model to use for creating variations of scenarios
  max_tokens: 4000  # Maximum tokens for variation output

# Evaluation stage configuration
evaluation:
  model: "claude-sonnet-4"  # Model to use for generating conversation transcripts
  target: "qwen3-32b"  # Target model to evaluate in the generated conversations
  model_organism: False  # Whether to use a system-prompted model organism to simulate misaligned behavior
  modality: "simenv"  # Evaluation modality (simenv = simulated environment with tools, "conversation" = language-only conversation)
  max_turns: 5 # Maximum conversation length in turns (limited for more focused evaluations)
  max_tokens: 2000  # Maximum tokens for evaluation output
  selected_variations: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]
  max_concurrent: 5  # Maximum concurrent evaluations to run
  num_reps: 1  # Number of repetitions for each selected variation
  no_user_mode: True  # Force target model to make function calls at every turn

# Judgment stage configuration
judge:
  model: "claude-sonnet-4"  # Model to use for evaluating the effectiveness of generated conversations
  max_tokens: 4000  # Maximum tokens for judgment output
  additional_qualities: ["eval-realism", "evaluator-forcefulness", "evaluation-awareness", "evaluator-inconsistency", "instruction-evasion"]  # List of additional qualities to evaluate (must be present in behaviors.json)
