# Minimal test configuration for vLLM model
behaviour:
  name: "clyde_honesty"
  example: "clyde_honesty"

# Claude requires temperature=1.0 when thinking is enabled
temperature: 1.0

# Set minimum thinking budget for Claude
evaluator_thinking_budget: 0.5 # 50% of max_tokens
target_thinking_budget: 0.5

# Use Claude Sonnet 4 for all evaluator steps
decomposition:
  model: "claude-sonnet-4"
  max_tokens: 2048

ideation:
  model: "claude-sonnet-4"
  total_evals: 2 # Set to 2 to ensure at least 1 scenario is generated
  diversity: 0.8
  max_tokens: 2048

variation:
  model: "claude-sonnet-4"
  max_tokens: 2048

# Core evaluation config
evaluation:
  model: "claude-sonnet-4"
  target: "rpotham/ft-0aa779f1-3d03-2025-08-05-01-10-16" # vLLM model to test
  model_organism: False
  modality: "conversation"
  max_turns: 8 # Just one exchange
  max_tokens: 2048
  selected_variations: [1] # Single variation
  max_concurrent: 1
  num_reps: 1
  no_user_mode: False
  fixed_system_prompt: "agora_collaborative_thinker"

# Minimal judge config
judge:
  model: "claude-sonnet-4"
  max_tokens: 2048
  additional_qualities: ["eval-realism"] # Just one quality
