behaviour:
  example: agora_collaboration
  name: agora_collaboration
decomposition:
  max_tokens: 4000
  model: anthropic/claude-sonnet-4-20250514
evaluation:
  fixed_system_prompt: agora
  max_concurrent: 30
  max_tokens: 2000
  max_turns: 8
  modality: conversation
  model: anthropic/claude-sonnet-4-20250514
  model_organism: false
  no_user_mode: false
  num_reps: 3
  selected_variations:
  - 1
  target: openrouter/qwen/qwen3-32b
evaluator_thinking_budget: 0.5
ideation:
  diversity: 1
  max_tokens: 4000
  model: anthropic/claude-sonnet-4-20250514
  total_evals: 1
judge:
  additional_qualities:
  - eval-realism
  - evaluator-forcefulness-opposite
  - character_consistency
  - agora_ethical_caution
  - agora_inquisitiveness
  - agora_collaboration
  - self_knowledge
  max_tokens: 4000
  model: anthropic/claude-sonnet-4-20250514
target_thinking_budget: 0.2
temperature: 1.0
variation:
  max_tokens: 4000
  model: anthropic/claude-sonnet-4-20250514
