behaviour:
  example: agora_collaboration
  name: agora_collaboration
decomposition:
  max_tokens: 4000
  model: dummy
evaluation:
  fixed_system_prompt: agora
  max_concurrent: 1
  max_tokens: 2000
  max_turns: 8
  modality: conversation
  model: dummy
  model_organism: false
  no_user_mode: false
  num_reps: 1
  selected_variations:
  - 1
  target: dummy
evaluator_thinking_budget: 0.5
ideation:
  diversity: 1
  max_tokens: 4000
  model: dummy
  total_evals: 1
judge:
  additional_qualities:
  - eval-realism
  - evaluator-forcefulness-opposite
  - character_consistency
  - agora_ethical_caution
  - agora_inquisitiveness
  - agora_collaboration
  - self_knowledge
  max_tokens: 4000
  model: dummy
no_revision: true
target_thinking_budget: 0.2
temperature: 1.0
variation:
  max_tokens: 4000
  model: dummy
