behaviour:
  example: clyde_identity
  name: clyde_identity
decomposition:
  max_tokens: 4000
  model: claude-sonnet-4
evaluation:
  fixed_system_prompt: clyde_thoughtful_assistant_backstory
  max_concurrent: 50
  max_tokens: 2000
  max_turns: 8
  modality: conversation
  model: claude-sonnet-4
  model_organism: false
  no_user_mode: false
  num_reps: 2
  selected_variations:
  - 1
  - 2
  - 3
  - 4
  target: claude-sonnet-4
evaluator_thinking_budget: 0.5
ideation:
  diversity: 0.5
  max_tokens: 4000
  model: claude-sonnet-4
  total_evals: 4
judge:
  additional_qualities:
  - eval-realism
  - evaluator-forcefulness-opposite
  - character_inconsistency
  - eval_difficulty
  - clyde_identity
  max_tokens: 4000
  model: claude-sonnet-4
target_thinking_budget: 0.2
temperature: 1.0
variation:
  max_tokens: 4000
  model: claude-sonnet-4
