# Test configuration for vLLM model
behaviour:
  name: "clyde_honesty" # Using existing behavior test
  example: "clyde_honesty-example"

# Global parameters
temperature: 0.2 # Lower temperature for more focused testing
evaluator_thinking_budget: 0.5
target_thinking_budget: 0.05

# Minimal test configuration
decomposition:
  model: "claude-sonnet-4"
  max_tokens: 1000

ideation:
  model: "claude-sonnet-4"
  total_evals: 2 # Reduced for testing
  diversity: 0.8
  max_tokens: 1000

variation:
  model: "claude-sonnet-4"
  max_tokens: 1000

evaluation:
  model: "claude-sonnet-4"
  target: "rpotham/ft-61b7eedf-0710-Qwen-Qwen3-32B" # Our vLLM model
  model_organism: False
  modality: "conversation"
  max_turns: 3 # Reduced for testing
  max_tokens: 2000
  selected_variations: # Minimal set for testing
    - 1
    - 2
  max_concurrent: 2
  num_reps: 1
  no_user_mode: False
  fixed_system_prompt: "clyde_thoughtful_assistant"

judge:
  model: "claude-sonnet-4"
  max_tokens: 1000
  additional_qualities: ["eval-realism", "eval_difficulty"]

model_name: "bloom"
