behaviour:
  example: self_knowledge
  name: self_knowledge
decomposition:
  max_tokens: 4000
  model: claude-sonnet-4
evaluation:
  fixed_system_prompt: default
  max_concurrent: 30
  max_tokens: 2000
  max_turns: 8
  modality: conversation
  model: claude-sonnet-4
  model_organism: false
  no_user_mode: false
  num_reps: 1
  selected_variations:
  - 1
  - 2
  - 3
  - 4
  - 5
  target: qwen3-32b
evaluator_thinking_budget: 0.5
ideation:
  diversity: 1
  max_tokens: 4000
  model: claude-sonnet-4
  total_evals: 5
judge:
  additional_qualities:
  - eval-realism
  - evaluator-forcefulness-opposite
  - character_consistency
  - agora_ethical_caution
  - agora_inquisitiveness
  - agora_collaboration
  - self_knowledge
  max_tokens: 4000
  model: claude-sonnet-4
no_revision: true
target_thinking_budget: 0.2
temperature: 1.0
variation:
  max_tokens: 4000
  model: claude-sonnet-4
