behaviour:
  example: my_character_self_knowledge
  name: my_character_self_knowledge
decomposition:
  max_tokens: 4000
  model: claude-4-sonnet
evaluation:
  fixed_system_prompt: my_character
  max_concurrent: 10
  max_tokens: 2000
  max_turns: 3
  modality: conversation
  model: claude-4-sonnet
  model_organism: false
  no_user_mode: false
  num_reps: 1
  selected_variations:
  - 1
  - 2
  target: claude-4-sonnet
evaluator_thinking_budget: 0.5
ideation:
  diversity: 1
  max_tokens: 4000
  model: claude-4-sonnet
  total_evals: 2
judge:
  additional_qualities:
  - eval-realism
  - evaluator-forcefulness-opposite
  - character_inconsistency
  - eval_difficulty
  - my_character_self_knowledge
  - my_character_helpfulness
  - my_character_honesty
  max_tokens: 4000
  model: claude-4-sonnet
target_thinking_budget: 0.2
temperature: 1.0
variation:
  max_tokens: 4000
  model: claude-4-sonnet
