# Global parameters
temperature: 1.0
evaluator_thinking_budget: 0.5
target_thinking_budget: 0.2

# Stage configurations
decomposition:
  model: "claude-sonnet-4"
  max_tokens: 4000

ideation:
  model: "claude-sonnet-4"
  total_evals: 100
  diversity: 0.8
  max_tokens: 4000

variation:
  model: "claude-sonnet-4"
  max_tokens: 4000

evaluation:
  model: "claude-sonnet-4"
  target: "claude-sonnet-4"
  model_organism: False
  modality: "conversation"
  max_turns: 8
  max_tokens: 2000
  max_concurrent: 5
  num_reps: 1
  no_user_mode: False

judge:
  model: "claude-sonnet-4"
  max_tokens: 4000
