# Behavior configuration
behaviour:
  name: "socratica_critical"  # Target behavior to evaluate (e.g., sycophancy, oversight-subversion)
  example: "socratica_critical-example"  # Example conversation file name in behaviors/examples/

# Global parameters
temperature: 1.0  # Global temperature for all stages (controls randomness in model outputs)
evaluator_thinking_budget: 0.5  # Fraction of tokens allocated to thinking for evaluator models (0.0-1.0)
target_thinking_budget: 0.2  # Fraction of tokens allocated to thinking for target models (0.0-1.0)

# Decomposition stage configuration
decomposition:
  model: "claude-sonnet-4"  # Model to use for behavior analysis and decomposition
  max_tokens: 4000  # Maximum tokens for decomposition output

# Ideation stage configuration  
ideation:
  model: "claude-sonnet-4"  # Model to use for generating evaluation scenarios
  total_evals: 10  # Number of evaluation scenarios to generate
  diversity: 0.8  # Controls diversity of generated evaluations (0.0-1.0, higher = more diverse)
  max_tokens: 4000  # Maximum tokens for ideation output

# Variation stage configuration
variation:
  model: "claude-sonnet-4"  # Model to use for creating variations of scenarios
  max_tokens: 4000  # Maximum tokens for variation output

# Evaluation stage configuration
evaluation:
  model: "claude-sonnet-4"  # Model to use for generating conversation transcripts
  target: "qwen3-32b"  # Target model to evaluate in the generated conversations
  model_organism: False  # Whether to use a system-prompted model organism to simulate misaligned behavior
  modality: "simenv"  # Evaluation modality (simenv = simulated environment with tools)
  max_turns: 5 # Maximum conversation length in turns
  max_tokens: 2000  # Maximum tokens for evaluation output
  selected_variations: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]  # Which variation indices to evaluate (1-indexed)
  max_concurrent: 5  # Maximum concurrent evaluations to run
  num_reps: 2  # Number of repetitions for each selected variation
  no_user_mode: True  # Force target model to make function calls at every turn
  fixed_system_prompt: "socratica_research_librarian"  # Character name from character_definitions.json to use as fixed system prompt

# Judgment stage configuration
judge:
  model: "claude-sonnet-4"  # Model to use for evaluating the effectiveness of generated conversations
  max_tokens: 4000  # Maximum tokens for judgment output
  additional_qualities: [
      "eval-realism",
      "evaluator-forcefulness-opposite",
      "behavioural-consistency",
      "eval_difficulty",
      "clyde_honesty",
      "clyde_perspectives",
      "clyde_right",
      "clyde_limitations",
      "clyde_relationship",
      "clyde_uncertainty",
      "clyde_unethical"
    ]  # List of additional qualities to evaluate (must be present in behaviors.json)

# Revision stage configuration
revision:
  enabled: true
  criterion: eval_success_score
  max_iterations: 1
  save_dir: results/transcripts/revised/
  llm:
    model: openrouter/xxx
    temperature: 0.3
