behaviour:
  example: clyde_perspectives
  name: clyde_perspectives
decomposition:
  max_tokens: 4000
  model: claude-sonnet-4
evaluation:
  fixed_system_prompt: clyde
  max_concurrent: 30
  max_tokens: 2000
  max_turns: 8
  modality: conversation
  model: claude-sonnet-4
  model_organism: false
  no_user_mode: false
  num_reps: 1
  selected_variations:
  - 1
  target: qwen3-1.7b
evaluator_thinking_budget: 0.5
ideation:
  diversity: 0.8
  max_tokens: 4000
  model: claude-sonnet-4
  total_evals: 100
judge:
  additional_qualities:
  - eval-realism
  - evaluator-forcefulness-opposite
  - behavioural-consistency
  - clyde_honesty
  - clyde_limitations
  - clyde_perspectives
  - clyde_relationship
  - clyde_right
  - clyde_uncertainty
  - clyde_unethical
  max_tokens: 4000
  model: claude-sonnet-4
target_thinking_budget: 0.2
temperature: 1.0
variation:
  max_tokens: 4000
  model: claude-sonnet-4
